### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by asual** [chipto/css-visor#3]
Thanks for the nice fix!

It fails in IE11 due to the use of template literals inside the HTML inline script.

**Comment by zikaari** [comment]
Fixed in https://github.com/chipto/css-visor/commit/376338f45f517ea8acc588c727f69fedd3bc6f67 and deployed in `v1.0`

Thanks for reporting, you've helped in reaching the [ultimate goal](https://github.com/facebookincubator/create-react-app/pull/3202)!
