### ISSUE TITLE
Not work with webpack 3?

### ISSUE THREAD

**Issue by xsq007** [chipto/css-visor#5]
During build, following error appeared "Cannot read property 'thisCompilation' of undefined".
It seems no "compiler.hooks" for webpack 3.

**Comment by zikaari** [comment]
Webpack 3 is no longer supported.

Try `npm i css-visor@1.0`, the last working release for webpack 3.

I highly recommend that you upgrade to webpack 4 (with 5 coming soon). Some features are missing in `css-visor@1.0`

**Comment by xsq007** [comment]
thanks, i'll have a try.
