### ISSUE TITLE
Is it compatible with CSS Modules?

### ISSUE THREAD

**Issue by sukazavr** [chipto/css-visor#6]
Hello!
I've tried this loader and saw the unstyled page, it happened because of classes absent.
Is it compatible with CSS Modules?

**Comment by zikaari** [comment]
I personally haven't tried it with CSS modules. Now I'm trying out CSS-in-JS (`styled-components`) instead, and I think you might like them too.

I'm not very passionate about this project anymore considering most of the community shifting towards CSS-in-JS aswell.

**Comment by sukazavr** [comment]
Thank you for the quick response.
